#!/bin/bash
set -ex
jupyter kernelspec install /srv/conda/envs/notebook/etc/notebook/kernels/root/ --user

wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
sudo dpkg -i cvmfs-release-latest_all.deb
rm -f cvmfs-release-latest_all.deb
sudo apt-get update
sudo apt-get install cvmfs
